questionWords = {'was', ' when', 'would', ' does', ' is', 'am', ' where', ' how', 'why', 'what', 'could', ' do',
                 'whose', 'are', ' why', 'where', 'when', 'how', 'which', 'were', 'who', 'whom', 'should', 'wanna',
                 ' can'}
stopWordZ = {'onto', 'since', 'first', 'our', 'o', 'i', 'almost', 'wouldn', 'next', "isn't", 'eleven', "aren't", 'part',
             'once', 'nothing', 'another', 'go', 'below', 'sixty', 'too', 'about', 'every', 'elsewhere', 'very',
             'somewhere', 'its', 'quite', "wouldn't", ' in ', 'one', 'became', 'empty', 'have', "doesn't", 'ten',
             'shan', 'hereupon', 'll', 'although', 'hereby', 'it', 'do', 'twenty', 'anyhow', 'such', 'throughout',
             'either', 'whereby', 'regarding', 'doing', 'whether', 'often', 'whole', 'at', 'beforehand', 'a', 'y',
             'herein', "you're", 'whenever', 'me', 'unless', 'wherein', 'during', 'forty', 'up', 'are', "couldn't",
             'used', 'really', 'himself', 'she', 'itself', 'side', 'sometime', 'whence', 'us', 'ourselves', 'somehow',
             'thereafter', 'become', 'call', 'via', 'be', 'upon', 'toward', 'not ', 'less', 'for ', 'there', 'into',
             'through', 'take', 'moreover', 'thus', 'hereafter', 'my', 'eight', 'say', 'shouldn', 'keep', 'whose',
             'own', 'myself', 'anyway', 'least', 'perhaps', 'they', 'everyone', 'thereupon', 'get', "hasn't", 'across',
             'which', 'mostly', 'might', "you've", 'most', 'per', 'must', 'done', 'see', 'each', 'their', 'never',
             'the', 'm', 'from', 'enough', 'except', 'why', 'this', 'beyond', 'when', 'namely', 'two', 're', 'for',
             'were', 'whereafter', 'having', "didn't", 'has', 'does', 'always', "weren't", 'd', 'third', 'various',
             'would', 'nobody', 'wherever', 'among', 'being', 'hers', 'both', 'mustn', "wasn't", "she's", 'something',
             'afterwards', 'after', 'together', 'is', 'without', 'whereas', 'isn', 'thru', 'off', 't', 'wasn', 'using',
             'around', 'on', ' or ', 'under', 'because', 'where', 'all', 'back', 'put', 'rather', 'mightn',
             'ain', 'whom', 'could', 'former', "won't", 'will', 'any', 'few', 'latter', 'again', 'him', 'top',
             "mustn't", 'and', 'give', 'only', 'no', 'besides', 'three', 'he', 'anyone', 'we', 'seeming', 'if',
             "should've", 'six', 'along', 'nine', "you'd", 'amongst', 'ours', 'whatever', 'some', 'an', 'here', 'am',
             'others', 'whereupon', 'them', 'but', 'meanwhile', 'therein', 'as', 'show', 'herself', 'further',
             'already', "haven't", "shouldn't", 's', 'however', 'now', 'becoming', 'seem', 'in', 'so', 'noone', 'until',
             'may', 'out', 'move', 'bottom', 'same', "it's", 'while ', 'then', 'who', 'thence', 'nevertheless',
             'someone', "you'll", 'fifty', 'didn', 'those', 'amount', 'therefore', 'neither', 'beside', 'four',
             'many', 'twelve', 'did', 'ma', 'make', 'much', 'towards', "needn't", 'his', 'within', "mightn't", 'you',
             'to', 'fifteen', 'how', 'thereby', 'of', 'down', 've', 'while', 'yourself', 'above', 'anything',
             'still', 'seemed', 'anywhere', 'whoever', 'just', 'before', 'mine', 'these', 'other', 'whither', 'been',
             'can', 'latterly', 'made', 'your', 'behind', "that'll", ' else ', 'yourselves', 'themselves', 'nor',
             'though', "hadn't", 'indeed', 'even', 'hence', 'aren', 'ca', 'over', 'with', 'due', 'otherwise', ' is ',
             ' and ', 'seems', 'yet', 'hadn', 'everywhere', 'needn', 'full', 'that', 'nowhere', 'between',
              'none', 'had', 'name', 'cannot', 'by', 'hasn', 'hundred', 'last', 'also', 'ever', 'front',
             'couldn', 'doesn', 'don', 'weren', 'was', 'should', 'becomes', 'theirs', "shan't", "don't", 'more', 'her',
             'everything', 'formerly', 'haven', 'than', 'several', 'what', 'five', 'sometimes', 'yours'}
